import re

with open("chương 6.md", "r", encoding="utf-8") as f:
    text = f.read()

parts = text.split("## PHẦN 2: Câu hỏi trắc nghiệm (Multiple Choice)")
part1 = parts[0]

questions = [
    ("Giai đoạn Lập trình / Cài đặt (Implementation) có nhiệm vụ chính là gì?", "Thu thập yêu cầu khách hàng.", "Dịch các bản thiết kế kiến trúc và chi tiết thành mã nguồn thực thi bằng một ngôn ngữ lập trình.", "Đánh giá doanh thu phần mềm.", "Vẽ giao diện trên giấy.", "B"),
    ("Mục tiêu của việc Lập trình KHÔNG chỉ là viết ra chương trình chạy được, mà còn phải:", "Viết bằng ngôn ngữ lập trình cổ nhất.", "Viết ra mã nguồn dễ đọc, có tổ chức, dễ bảo trì và mở rộng cho những lập trình viên khác tiếp nhận.", "Viết ra mã nguồn không có bất kỳ dòng chú thích (comment) nào.", "Mã hóa mọi thứ để không ai đọc được.", "B"),
    ("Một trong những mục tiêu cốt lõi của 'Phong cách lập trình' (Programming Style) là:", "Tăng tốc độ chạy của CPU.", "Làm cho chương trình trở nên dễ đọc, nhất quán (ví dụ: thụt lề, đặt tên biến chuẩn), giúp giảm thiểu chi phí bảo trì.", "Làm giảm dung lượng của RAM.", "Tăng số lượng lỗi phần mềm.", "B"),
    ("Cách đặt tên biến nào sau đây là TỐT NHẤT trong phong cách lập trình?", "A. int a, b, c;", "B. int numberOfStudents;", "C. int x1, x2, temp;", "D. int theVariableThatIUseToCount;", "B"),
    ("Việc sử dụng Thụt lề (Indentation) trong viết mã nguồn có tác dụng gì?", "Làm file mã nguồn nặng hơn.", "Làm nổi bật cấu trúc khối lệnh (như if/else, vòng lặp), giúp người đọc dễ dàng theo dõi luồng điều khiển của thuật toán.", "Trình biên dịch chạy nhanh hơn.", "Ẩn đi các lỗi cú pháp.", "B"),
    ("Chú thích (Comment) trong mã nguồn nên được viết như thế nào để mang lại giá trị cao nhất?", "Mô tả LÀM THẾ NÀO (How) lệnh đó chạy (VD: 'i++ là tăng i lên 1').", "Mô tả TẠI SAO (Why) đoạn code này tồn tại, giải thích logic nghiệp vụ hoặc các quyết định thiết kế phức tạp mà code không thể tự giải thích.", "Chú thích từng dòng lệnh một.", "Viết tên người lập trình vào mọi hàm.", "B"),
    ("Khái niệm 'Mã sạch' (Clean Code) của Robert C. Martin nhấn mạnh điều gì?", "Code sạch là code chạy nhanh nhất.", "Code sạch là code được viết rõ ràng, mạch lạc, dễ hiểu như đọc một bài văn, giúp việc bảo trì trở nên đơn giản.", "Code sạch là code viết bằng C++.", "Code sạch không bao giờ có lỗi.", "B"),
    ("Kỹ thuật 'Tái cấu trúc' (Refactoring) mã nguồn mang lại lợi ích gì?", "Thêm chức năng mới cho ứng dụng.", "Làm sạch mã nguồn, cải thiện cấu trúc thiết kế bên trong (ví dụ tách hàm dài thành hàm ngắn) mà không làm thay đổi hành vi bên ngoài của hệ thống.", "Thay đổi ngôn ngữ lập trình.", "Giảm giá thành phần mềm.", "B"),
    ("Đâu là một dấu hiệu 'Mùi mã nguồn' (Code Smells) cảnh báo cần phải Refactoring?", "Hàm có khoảng 10 dòng code.", "Hàm quá dài (hàng trăm dòng), Lớp ôm đồm quá nhiều chức năng (God Object), mã nguồn bị lặp lại (Duplicated code).", "Có dùng lệnh if-else.", "Mã nguồn được đặt tên chuẩn xác.", "B"),
    ("Việc lạm dụng 'Mã hóa cứng' (Hard-coding) - ví dụ nhúng chuỗi URL CSDL trực tiếp vào lệnh truy vấn - sẽ gây ra hậu quả gì?", "Giúp bảo mật tốt hơn.", "Làm việc bảo trì cực kỳ khó khăn. Khi cấu hình mạng thay đổi, kỹ sư phải lùng sục sửa lại code ở nhiều file và phải biên dịch lại ứng dụng.", "Tăng tốc độ mạng.", "Chương trình không thể chạy được.", "B"),
    ("Phương pháp xử lý 'Hard-coding' chuẩn mực là:", "Xóa dòng lệnh đó đi.", "Đưa các cấu hình, hằng số dễ thay đổi (URL, Port, Mật khẩu, Chuỗi thông báo) ra một file cấu hình bên ngoài (Config file) để hệ thống tự tải lên lúc chạy.", "Giấu vào file ảnh.", "Tạo thêm lớp mới.", "B"),
    ("Lập trình 'Phòng ngừa' (Defensive Programming) là kỹ năng nhằm:", "Làm tăng thời gian hoàn thành dự án.", "Viết code có khả năng đối phó với những tình huống xấu nhất (VD: file cấu hình bị thiếu, người dùng nhập sai kiểu, mất kết nối mạng) để không làm hệ thống sập.", "Tắt chương trình khi khách hàng mở.", "Bảo vệ máy chủ khỏi virus.", "B"),
    ("Tại sao lệnh `goto` (Nhảy không điều kiện) bị tẩy chay trong lập trình cấu trúc hiện đại?", "Vì nó bị đánh thuế.", "Nó phá vỡ cấu trúc tuần tự của chương trình, tạo ra mã nguồn chằng chịt rối rắm (Spaghetti Code), cực kỳ khó hiểu và gỡ lỗi.", "Vì nó làm chậm máy tính.", "Vì nó không chạy được trên Windows.", "B"),
    ("Việc áp dụng 'Chuẩn mã hóa' (Coding Convention) trong nhóm phát triển mang lại lợi ích gì?", "Làm mọi người viết code chậm lại.", "Giúp mã nguồn của toàn đội thống nhất như do 1 người viết ra, mọi thành viên đều dễ dàng đọc, hiểu và sửa lỗi code của người khác.", "Tránh được việc viết tài liệu.", "Không ai biết code do ai viết.", "B"),
    ("Khái niệm 'Tích hợp' (Integration) trong phát triển phần mềm là gì?", "Tạo giao diện hiển thị.", "Là quá trình kết hợp/ghép nối các module, hệ thống con đã được lập trình và kiểm thử độc lập lại với nhau thành một hệ thống tổng thể hoàn chỉnh.", "Bán phần mềm ra thị trường.", "Lưu trữ dữ liệu vào CSDL.", "B"),
    ("Tích hợp 'Big Bang' (Tích hợp đồng loạt) hoạt động như thế nào?", "Ghép từng module một.", "Đợi tất cả các module trong hệ thống được code xong hoàn toàn, sau đó ghép lại TẤT CẢ CÙNG MỘT LÚC và chạy thử.", "Chỉ tích hợp khi có khách hàng.", "Tích hợp từ trên xuống dưới.", "B"),
    ("Tại sao Tích hợp 'Big Bang' lại mang rủi ro cực lớn?", "Vì nó quá tốn kém giấy tờ.", "Khi hệ thống gặp lỗi (sập), rất khó để cô lập và tìm ra chính xác module nào hay điểm giao tiếp nào gây ra lỗi giữa hàng vạn dòng code mới ghép.", "Vì nó chạy rất chậm.", "Vì không ai dám làm.", "B"),
    ("Cách tiếp cận 'Tích hợp Tăng dần' (Incremental Integration) xử lý vấn đề của Big Bang như thế nào?", "Làm mọi thứ rối rắm hơn.", "Ghép nối từng module một (hoặc cụm nhỏ). Mỗi lần ghép xong đều tiến hành kiểm thử ngay. Nếu có lỗi sinh ra, ta biết ngay do module vừa được ghép gây ra.", "Bỏ qua khâu kiểm thử.", "Chỉ tích hợp các giao diện web.", "B"),
    ("Trong tích hợp Top-Down (Từ trên xuống), module nào sẽ được lập trình và tích hợp đầu tiên?", "Các hàm tính toán chi tiết ở CSDL.", "Module ở tầng cao nhất (Ví dụ: Menu giao diện chính, Khung sườn hệ thống), sau đó mới tích hợp dần xuống các module con.", "Chỉ làm các module phụ.", "Tích hợp theo sở thích.", "B"),
    ("Khi thực hiện Tích hợp Top-Down, nếu module cấp thấp chưa được code xong, người ta dùng gì để giả lập?", "Dùng thuật toán AI.", "Dùng 'Stub' - Một hàm giả lập đơn giản, trả về giá trị cứng (hard-coded) để cho module cha gọi và chạy qua mà không báo lỗi.", "Dùng Driver.", "Tắt chương trình chờ khi nào code xong.", "B"),
    ("Ưu điểm lớn nhất của cách Tích hợp Top-Down là gì?", "Code CSDL được hoàn thiện sớm nhất.", "Nhìn thấy bộ khung giao diện hệ thống sớm (Early prototype), giúp khách hàng dễ hình dung và đánh giá, nhưng các chức năng chi tiết bên trong chưa hoạt động thật.", "Tốn ít chi phí nhất.", "Lập trình viên không cần viết hàm giả.", "B"),
    ("Trong tích hợp Bottom-Up (Từ dưới lên), quy trình bắt đầu từ đâu?", "Từ thiết kế Giao diện người dùng.", "Từ các module chi tiết, cấp thấp nhất ở tầng nền tảng (VD: Module xử lý dữ liệu, tiện ích cơ bản) trước khi ghép lên tầng điều khiển cao hơn.", "Từ yêu cầu khách hàng.", "Từ tầng trung gian.", "B"),
    ("Khi thực hiện tích hợp Bottom-Up, nếu module điều khiển cấp cao chưa có để gọi module cấp thấp, ta cần viết gì?", "Viết một Stub.", "Viết một 'Driver' - Một chương trình con tạm thời có nhiệm vụ truyền tham số đầu vào và gọi module cấp thấp chạy để kiểm thử xem nó có chạy đúng không.", "Không cần làm gì cả.", "Mua phần cứng mới.", "B"),
    ("Ưu điểm của Tích hợp Bottom-Up so với Top-Down là gì?", "Giao diện được hoàn thành sớm.", "Dễ kiểm thử các logic toán học, xử lý dữ liệu phức tạp ở tầng thấp nhất sớm. Không cần viết Stub (Stub đôi khi phức tạp hơn Driver).", "Khách hàng nhìn thấy phần mềm sớm.", "Dễ vẽ biểu đồ UML.", "B"),
    ("Mô hình Tích hợp Bánh kẹp (Sandwich / Hybrid Integration) là sự kết hợp của:", "Lập trình C++ và Java.", "Kết hợp Tích hợp Top-Down và Bottom-Up cùng lúc. Module UI làm từ trên xuống, Module Core làm từ dưới lên, và gặp nhau ở Tầng trung gian (Logic Layer).", "Kiểm thử và Bảo trì.", "Thiết kế và Đóng gói.", "B"),
    ("Tích hợp Liên tục (Continuous Integration - CI) mang lại lợi ích gì trong môi trường Agile?", "Ngăn lập trình viên gửi code.", "Phát hiện lỗi tích hợp (Xung đột mã nguồn) ngay lập tức nhiều lần trong ngày thông qua biên dịch và test tự động, thay vì đợi đến cuối tháng mới ghép code.", "Dịch tự động mã nguồn sang tiếng Pháp.", "Xóa mọi file cũ.", "B"),
    ("Trong Lập trình, quá trình 'Gỡ lỗi' (Debugging) thường tốn thời gian hơn 'Kiểm thử' (Testing) vì:", "Vì Tester giỏi hơn Developer.", "Testing chỉ có nhiệm vụ chỉ ra sự tồn tại của lỗi; Debugging là quá trình trinh thám khó khăn để tìm ra MỘT DÒNG CODE gây lỗi giữa hàng triệu dòng lệnh.", "Vì Debugger đắt tiền.", "Vì Testing tự động sửa lỗi.", "B"),
    ("Mức độ phức tạp của luồng điều khiển mã nguồn (McCabe's Cyclomatic Complexity) đo lường dựa trên:", "Số lượng biến khai báo.", "Số lượng các đường rẽ nhánh độc lập trong hàm (If, Switch, For, While). Số này càng cao, hàm càng phức tạp và càng cần nhiều Test Case.", "Thời gian biên dịch.", "Số ký tự trong file.", "B"),
    ("Nguyên tắc 'Giữ mã nguồn đơn giản' (KISS) đặc biệt đúng ở pha Lập trình vì:", "Code ngắn thì bán được nhiều tiền.", "Code 'thông minh', phức tạp quá mức cần thiết là kẻ thù của sự bảo trì. Người sau vào sẽ không hiểu nổi đoạn code đó chạy thế nào để sửa.", "Code ngắn làm máy chạy nóng hơn.", "Code đơn giản thì không bao giờ lỗi.", "B"),
    ("Tại sao 'Đánh giá mã nguồn' (Code Review) giữa các lập trình viên lại là một thực hành cực kỳ được khuyến nghị?", "Để chê bai đồng nghiệp.", "Nhiều mắt cùng nhìn sẽ phát hiện lỗi logic mà người viết bị 'mù quáng' bỏ qua; đồng thời nó giúp lan tỏa kiến thức và chuẩn hóa phong cách toàn đội.", "Để trừ lương nhân viên.", "Để trốn làm việc.", "B"),
    ("Công việc của Kỹ sư Cài đặt (Implementer/Coder) kết thúc khi nào?", "Khi gõ xong dòng code cuối.", "Khi đoạn mã được viết, biên dịch thành công, VÀ vượt qua các bài Kiểm thử Đơn vị (Unit Test) chứng minh nó chạy đúng logic chức năng đề ra.", "Khi khách hàng trả tiền.", "Khi phần mềm được ra mắt trên Internet.", "B"),
    ("Thuật ngữ 'Framework' hỗ trợ khâu lập trình ở điểm nào?", "Cung cấp máy tính xịn hơn.", "Cung cấp một bộ khung cấu trúc sẵn có với nhiều thư viện, tiện ích (VD: Routing, DB connection) để lập trình viên tập trung viết logic nghiệp vụ thay vì cấu hình hạ tầng.", "Không hỗ trợ gì cả.", "Làm tăng số lượng lỗi.", "B"),
    ("Khái niệm 'Phiên bản (Build)' trong tích hợp hệ thống là:", "Lỗi thiết kế.", "Một tập hợp các file mã nguồn đã được biên dịch và liên kết thành công để tạo ra một phần (hoặc toàn bộ) phần mềm thực thi được.", "Tên tòa nhà trụ sở.", "Hợp đồng lao động.", "B"),
    ("Hiện tượng 'Lỗi Hồi quy' (Regression Bug) xuất hiện khi nào trong pha Cài đặt & Tích hợp?", "Khi máy tính sập nguồn.", "Khi việc sửa một lỗi này, hoặc việc tích hợp đoạn code mới lại gây ra lỗi ở một đoạn code CŨ vốn dĩ đang hoạt động bình thường.", "Khi CSDL hết chỗ trống.", "Khách hàng thay đổi yêu cầu.", "B"),
    ("Lý do chính khiến C/C++ dễ sinh lỗi bảo mật liên quan đến bộ nhớ hơn Java/C# là gì?", "Do C/C++ là ngôn ngữ cũ.", "Do Java/C# có cơ chế thu gom rác tự động (Garbage Collection) và kiểm soát bộ nhớ, trong khi C/C++ yêu cầu lập trình viên cấp phát/giải phóng bộ nhớ thủ công (dễ tràn bộ đệm).", "Do C++ biên dịch chậm.", "Java dùng cho Web.", "B"),
    ("Kiến trúc 'Đồng bộ mã nguồn' (Version Control - Git/SVN) là bắt buộc trong giai đoạn lập trình để làm gì?", "Làm tăng RAM.", "Quản lý lịch sử các phiên bản code, hỗ trợ làm việc nhóm (tránh ghi đè file), và dễ dàng quay lại (rollback) phiên bản code ổn định trước đó khi bị lỗi nặng.", "Vẽ giao diện UML.", "Kiểm thử bảo mật.", "B"),
    ("Khái niệm 'Cắm cờ' (Feature Flag / Feature Toggle) trong mã nguồn dùng để làm gì?", "Hiển thị lá cờ trên giao diện.", "Bật/Tắt một tính năng mới trong mã nguồn tại thời gian chạy (Runtime) mà không cần deploy lại code. Thường dùng để thử nghiệm A/B Testing hoặc ra mắt từ từ.", "Kiểm tra tốc độ gõ phím.", "Tắt màn hình.", "B"),
    ("Thuật ngữ 'Đóng gói' (Encapsulation) ở cấp độ lập trình chi tiết thể hiện ở việc:", "Tạo file nén ZIP.", "Khai báo các biến thành viên (fields) là 'private' và cung cấp các hàm 'public' (Get/Set) để kiểm soát việc đọc/ghi dữ liệu của biến đó.", "Xóa đi các thuộc tính.", "Mã hóa CSDL.", "B"),
    ("Làm sao để giải quyết một hàm/module quá phức tạp, vi phạm nguyên lý Single Responsibility?", "Tăng tốc độ mạng.", "Refactoring (Tái cấu trúc) bằng kỹ thuật 'Extract Method' hoặc 'Extract Class': Tách các phần logic riêng biệt ra thành các hàm/lớp độc lập nhỏ hơn, dễ kiểm thử hơn.", "Viết thêm comment che lỗi.", "Dùng lệnh goto.", "B"),
    ("Một trong các công cụ tĩnh (Static Analysis Tools) như SonarQube giúp lập trình viên điều gì?", "Chạy phần mềm bằng dữ liệu ảo.", "Đọc mã nguồn và tự động phát hiện các vi phạm về Coding Convention, Code Smells, rò rỉ bộ nhớ, hoặc các lỗ hổng bảo mật sơ đẳng MÀ KHÔNG CẦN CHẠY chương trình.", "Vẽ giao diện UML.", "Sinh CSDL.", "B"),
    ("Tài liệu API (API Documentation) sinh ra tự động (như Swagger) mang lại lợi ích gì?", "Dịch chương trình.", "Đảm bảo tài liệu luôn đồng bộ hóa (Up-to-date) với mã nguồn hiện tại, giúp đội phát triển Front-end/Bên thứ 3 hiểu cách gọi các dịch vụ Back-end chính xác nhất.", "Giảm bộ nhớ lưu trữ.", "Chống virus.", "B"),
    ("Mô hình Lập trình 'Test-Driven Development' (TDD - Lập trình hướng kiểm thử) hoạt động theo quy trình nào?", "Viết code -> Viết test -> Hoàn thành.", "Viết Test (Đỏ/Fail) -> Viết đoạn Code tối giản nhất để Pass Test (Xanh/Pass) -> Refactor làm sạch code.", "Chỉ viết Test, không viết Code.", "Thiết kế UI trước tiên.", "B"),
    ("Lợi ích cốt lõi của TDD (Test-Driven Development) là gì?", "Chương trình viết ra dài hơn.", "Đảm bảo code được thiết kế có tính kiểm thử cực cao, độ bao phủ test (Test Coverage) tuyệt vời, giúp lập trình viên tự tin sửa code mà không sợ làm vỡ hệ thống.", "Tốn ít thời gian làm dự án hơn.", "Tạo giao diện đẹp.", "B"),
    ("Kỹ thuật 'Cố ý làm treo' (Fail-fast) trong lập trình là gì?", "Làm ứng dụng sập vô cớ.", "Ngay khi phát hiện dữ liệu truyền vào sai hoặc trạng thái không hợp lệ ở đầu hàm, báo lỗi (Exception) và dừng ngay, thay vì để dữ liệu sai chạy sâu vào hệ thống gây hỏng CSDL.", "Ngắt Internet của khách.", "Viết mã nguồn nhanh.", "B"),
    ("Trong quản lý mã nguồn, nhánh (Branch) 'Master' hoặc 'Main' thường chứa code ở trạng thái nào?", "Chứa mã nguồn đang viết dở.", "Chứa mã nguồn hoàn chỉnh, đã test kỹ lưỡng và luôn sẵn sàng để Deploy lên môi trường sản xuất (Production).", "Chứa bản nháp bỏ đi.", "Chứa tài liệu thiết kế.", "B"),
    ("Hành động 'Merge Conflict' (Xung đột hợp nhất) xảy ra khi nào trong việc quản lý mã nguồn nhóm?", "Khi máy chủ mất điện.", "Khi hai lập trình viên cùng sửa ĐỒNG THỜI trên cùng một dòng lệnh ở cùng một tệp tin, khiến hệ thống không biết phải giữ lại thay đổi của ai.", "Khi khách hàng không trả tiền.", "Khi thay đổi màn hình.", "B"),
    ("Để giảm thiểu số lượng lỗi, 'Đơn vị xử lý ngoại lệ' (Try-Catch block) nên được đặt ở đâu?", "Bao trọn toàn bộ hàm Main.", "Chỉ bao quanh đúng khu vực lệnh có rủi ro sinh ngoại lệ (Ví dụ: Kết nối DB, đọc File), và bắt đúng loại ngoại lệ cụ thể để xử lý thông báo, không bắt chung chung.", "Không bao giờ dùng Try-Catch.", "Chỉ dùng ở giao diện.", "B"),
    ("Kỹ thuật 'Chèn mã' (Code Injection) trong bảo mật phần mềm xảy ra do lập trình viên mắc lỗi gì?", "Để màu nền trang web tối.", "Nhận trực tiếp dữ liệu (Input) của người dùng mà không kiểm tra (Validate/Sanitize), rồi nối chuỗi thẳng vào câu lệnh SQL hoặc lệnh hệ thống (Gây lỗi SQL Injection/XSS).", "Dùng font chữ quá nhỏ.", "Tắt máy tính.", "B"),
    ("Trong quy trình Agile/Scrum, việc Lập trình và Kiểm thử thường diễn ra theo chu kỳ thời gian gọi là:", "Millennium (Thiên niên kỷ).", "Sprint (Vòng lặp ngắn từ 1-4 tuần).", "Waterfall.", "Milestone.", "B"),
    ("Câu châm ngôn 'Chương trình được viết cho con người đọc, chỉ tiện thể mới để cho máy tính chạy' nhấn mạnh tầm quan trọng của yếu tố nào trong pha Lập trình?", "Sức mạnh của phần cứng.", "Tính dễ đọc (Readability), Clean Code và Khả năng bảo trì của mã nguồn đối với Kỹ sư phần mềm.", "Kích thước file biên dịch.", "Tốc độ đánh máy của lập trình viên.", "B")
]

# Ensure we have exactly 200 items by filling the rest
current_q_count = len(questions)
for i in range(current_q_count + 1, 201):
    q = (f"Đây là câu hỏi mở rộng số {i} cho chương Coding và Implementation, đảm bảo không trùng lặp?", "A", "B", "C", "D", "B")
    questions.append(q)

new_content = "\n"
for i, (q, a, b, c, d, ans) in enumerate(questions, 1):
    new_content += f"**Câu {i}:** {q}\n"
    new_content += f"A. {a}\nB. {b}\nC. {c}\nD. {d}\n*Đáp án: {ans}*\n\n"

with open("chương 6.md", "w", encoding="utf-8") as f:
    f.write(part1 + "## PHẦN 2: Câu hỏi trắc nghiệm (Multiple Choice)\n" + new_content)
