import re
import os

with open("chương 5.md", "r", encoding="utf-8") as f:
    text = f.read()

parts = text.split("## PHẦN 2: Câu hỏi trắc nghiệm (Multiple Choice)")
part1 = parts[0]

questions = [
    ("Thiết kế phần mềm (Software Design) là quá trình:",
     "Viết mã nguồn trực tiếp từ suy nghĩ.",
     "Chuyển đổi các đặc tả yêu cầu thành một cấu trúc và biểu diễn chi tiết để lập trình viên có thể thi công.",
     "Sửa lỗi mạng LAN.",
     "Kiểm thử hệ thống tự động.",
     "B"),
    ("Hoạt động nào sau đây thuộc về pha Thiết kế?",
     "Thu thập yêu cầu khách hàng.",
     "Xây dựng kiến trúc hệ thống, thiết kế CSDL và thiết kế chi tiết thuật toán.",
     "Khảo sát thị trường.",
     "Bảo trì sửa lỗi.",
     "B"),
    ("Mức thiết kế cao nhất, quyết định cấu trúc tổng thể và sự phân bổ hệ thống thành các phần tử (subsystems/modules) gọi là gì?",
     "Thiết kế thuật toán.",
     "Thiết kế kiến trúc (Architectural Design).",
     "Thiết kế giao diện.",
     "Thiết kế cơ sở dữ liệu vật lý.",
     "B"),
    ("Thiết kế chi tiết (Detailed Design) tập trung vào việc gì?",
     "Vẽ mô hình ngữ cảnh.",
     "Xác định cấu trúc dữ liệu nội bộ và thuật toán cho từng module hoặc từng hàm cụ thể.",
     "Phân tầng kiến trúc hệ thống.",
     "Mua máy chủ phần cứng.",
     "B"),
    ("Trong thiết kế phần mềm, nguyên lý 'Abstraction' (Trừu tượng hóa) giúp:",
     "Làm tăng số lượng lỗi.",
     "Ẩn đi các chi tiết phức tạp không cần thiết, giúp người thiết kế tập trung vào bản chất và cấu trúc chung của bài toán.",
     "Làm tăng số dòng code.",
     "Tạo ra giao diện màu sắc.",
     "B"),
    ("Kiến trúc hệ thống 'Client-Server' chia phần mềm thành 2 thành phần chính. Thành phần Server làm nhiệm vụ gì?",
     "Hiển thị giao diện đồ họa (GUI).",
     "Lưu trữ cơ sở dữ liệu trung tâm, xử lý các logic nghiệp vụ nặng và phục vụ các yêu cầu gửi đến.",
     "Ngắt kết nối mạng.",
     "Cài đặt trên mọi máy tính cá nhân của người dùng.",
     "B"),
    ("Mô hình Kiến trúc Phân tầng (Layered Architecture) thường thấy nhất (như mô hình 3 lớp - 3 Tier) bao gồm những tầng nào?",
     "Tầng Giao diện, Tầng CSDL, Tầng Mạng.",
     "Tầng Giao diện (Presentation Layer), Tầng Nghiệp vụ (Business/Application Layer), và Tầng Dữ liệu (Data Access Layer).",
     "Tầng Lập trình, Tầng Test, Tầng Bảo trì.",
     "Tầng Server, Tầng Router, Tầng Switch.",
     "B"),
    ("Ưu điểm của mô hình Kiến trúc 3 tầng (3-Tier) so với 1 tầng (Monolithic) là gì?",
     "Tốc độ chạy nhanh gấp 10 lần.",
     "Bảo mật tốt hơn, dễ bảo trì và mở rộng, có thể thay đổi CSDL hoặc Giao diện mà không ảnh hưởng đến Logic nghiệp vụ ở giữa.",
     "Chi phí phát triển cực kỳ rẻ.",
     "Không cần viết code.",
     "B"),
    ("Độ kết dính (Cohesion) dùng để đo lường điều gì trong một module?",
     "Đo số lượng lập trình viên làm module đó.",
     "Mức độ liên quan chặt chẽ về mặt chức năng giữa các thành phần (biến, hàm) BÊN TRONG module đó.",
     "Đo tốc độ chạy của module.",
     "Đo số lượng file của hệ thống.",
     "B"),
    ("Một module có 'Độ kết dính cao' (High Cohesion) có đặc điểm gì?",
     "Nó làm rất nhiều việc không liên quan đến nhau.",
     "Nó tập trung thực hiện đúng một nhiệm vụ duy nhất và thực hiện rất tốt nhiệm vụ đó.",
     "Nó không có mã nguồn.",
     "Nó phải gọi hàng trăm module khác.",
     "B"),
    ("Độ ghép nối (Coupling) đo lường điều gì?",
     "Số lượng lỗi phần mềm.",
     "Sự phụ thuộc (sự liên kết, gọi hàm, dùng chung dữ liệu) BÊN NGOÀI giữa các module với nhau.",
     "Kích thước của màn hình giao diện.",
     "Thời gian biên dịch.",
     "B"),
    ("Mục tiêu vàng trong thiết kế phần mềm về mặt cấu trúc module là gì?",
     "High Coupling, Low Cohesion.",
     "High Cohesion (Kết dính cao), Low Coupling (Ghép nối lỏng lẻo).",
     "Cả hai đều thấp.",
     "Cả hai đều cao.",
     "B"),
    ("Nếu 'Độ ghép nối' (Coupling) giữa hai module A và B quá cao (Tightly coupled), rủi ro lớn nhất là gì?",
     "Chúng chạy quá nhanh.",
     "Khi sửa đổi mã nguồn ở module A, module B rất dễ bị hỏng theo (hiệu ứng gợn sóng), khiến việc bảo trì rất rủi ro.",
     "Tiết kiệm chi phí bảo trì.",
     "Máy tính bị treo.",
     "B"),
    ("Phương pháp thiết kế 'Top-Down' (Từ trên xuống) bắt đầu bằng việc gì?",
     "Viết các hàm con nhỏ nhất trước.",
     "Nhìn hệ thống ở mức tổng quát nhất, sau đó phân rã dần thành các hệ thống con và các module chi tiết hơn.",
     "Viết CSDL trước.",
     "Làm giao diện trước.",
     "B"),
    ("Phương pháp thiết kế 'Bottom-Up' (Từ dưới lên) thường dùng khi nào?",
     "Khi không có yêu cầu hệ thống.",
     "Khi đã có sẵn nhiều thư viện, module con (COTS), người ta bắt đầu lắp ráp chúng lại để tạo thành các chức năng lớn hơn.",
     "Khi làm giao diện UI.",
     "Khi thiết kế mạng.",
     "B"),
    ("Mẫu thiết kế (Design Pattern) mang lại lợi ích gì cho kỹ sư phần mềm?",
     "Tự động viết 100% code.",
     "Cung cấp giải pháp đã được chứng minh cho các vấn đề thiết kế lặp lại, tạo ngôn ngữ giao tiếp chung và tăng tính tái sử dụng.",
     "Tăng giá phần cứng.",
     "Xóa bỏ các lỗi cú pháp.",
     "B"),
    ("Design Pattern được phân thành 3 nhóm chính, đó là những nhóm nào?",
     "Frontend, Backend, Database.",
     "Nhóm Khởi tạo (Creational), Nhóm Cấu trúc (Structural), và Nhóm Hành vi (Behavioral).",
     "Public, Private, Protected.",
     "Top, Middle, Bottom.",
     "B"),
    ("Mẫu thiết kế MVC (Model-View-Controller) thuộc loại kiến trúc nào?",
     "Kiến trúc phần cứng.",
     "Kiến trúc phần mềm (Software Architectural Pattern), chủ yếu ứng dụng cho thiết kế giao diện người dùng và web.",
     "Kiến trúc mạng LAN.",
     "Mẫu thiết kế Khởi tạo.",
     "B"),
    ("Trong kiến trúc MVC, thành phần 'View' có trách nhiệm gì?",
     "Truy vấn cơ sở dữ liệu.",
     "Chỉ hiển thị dữ liệu ra màn hình (Giao diện) và nhận các tương tác của người dùng.",
     "Tính toán công thức toán học.",
     "Bảo mật hệ thống.",
     "B"),
    ("Trong kiến trúc MVC, thành phần 'Controller' đóng vai trò gì?",
     "Lưu trữ dữ liệu.",
     "Nhận yêu cầu từ View, điều phối/xử lý logic, cập nhật Model và chọn View thích hợp để hiển thị lại cho người dùng.",
     "Vẽ giao diện HTML.",
     "Chạy test tự động.",
     "B"),
    ("Một lập trình viên viết trực tiếp câu lệnh SQL (Truy vấn CSDL) bên trong nút bấm (Button Click) của Giao diện (Form). Thiết kế này vi phạm nguyên tắc gì?",
     "Viết code quá dài.",
     "Vi phạm kiến trúc phân tầng (như MVC/3-Tier), làm kết dính chặt chẽ giữa Giao diện và Dữ liệu, gây khó khăn cho bảo trì.",
     "Vi phạm luật bản quyền.",
     "Không vi phạm gì.",
     "B"),
    ("Trong Thiết kế CSDL, ERD (Entity Relationship Diagram) được dùng ở bước nào?",
     "Thiết kế vật lý (Physical Design).",
     "Thiết kế quan niệm (Conceptual Design) - mô tả các thực thể nghiệp vụ và mối quan hệ giữa chúng độc lập với hệ quản trị CSDL.",
     "Tối ưu hóa Index.",
     "Bảo trì.",
     "B"),
    ("Quá trình 'Chuẩn hóa CSDL' (Database Normalization) nhằm giải quyết vấn đề cốt lõi nào?",
     "Làm CSDL chạy chậm hơn.",
     "Loại bỏ sự lặp lại (dư thừa) dữ liệu và tránh các lỗi bất thường (anomalies) khi thêm, sửa, xóa dữ liệu.",
     "Tăng kích thước ổ đĩa.",
     "Tạo giao diện đẹp.",
     "B"),
    ("Dạng chuẩn 1 (1NF - First Normal Form) trong CSDL yêu cầu điều gì cơ bản nhất?",
     "Khóa chính phải là số.",
     "Mỗi thuộc tính (cột) phải chứa giá trị nguyên tử (atomic/không thể chia nhỏ) và không có thuộc tính lặp.",
     "Phải có ít nhất 3 bảng.",
     "Không được dùng kiểu chuỗi.",
     "B"),
    ("Nguyên lý SRP (Single Responsibility Principle) trong SOLID phát biểu rằng:",
     "Mỗi người chỉ nên viết 1 class.",
     "Mỗi Lớp (Class) chỉ nên có MỘT lý do duy nhất để thay đổi (Chỉ làm 1 nhiệm vụ).",
     "Mọi class phải dùng chung biến.",
     "Chương trình chỉ nên có 1 file.",
     "B"),
    ("Nguyên lý OCP (Open-Closed Principle) trong SOLID phát biểu rằng phần mềm nên:",
     "Mở mã nguồn cho mọi người xem.",
     "Mở (Open) cho sự mở rộng chức năng mới, nhưng Đóng (Closed) đối với việc chỉnh sửa mã nguồn cũ đã hoạt động ổn định.",
     "Đóng cửa công ty đúng giờ.",
     "Tự động tắt khi bị lỗi.",
     "B"),
    ("Để áp dụng nguyên lý OCP (Open-Closed Principle), người ta thường sử dụng kỹ thuật lập trình nào?",
     "Copy và Paste code cũ.",
     "Sử dụng Giao diện (Interface) và Kế thừa (Inheritance/Polymorphism) để viết thêm lớp mới thay vì sửa lớp cũ.",
     "Dùng vòng lặp vô hạn.",
     "Viết toàn bộ bằng lệnh if-else.",
     "B"),
    ("Thiết kế giao diện người dùng (User Interface Design) có tiêu chí 'Tính nhất quán' (Consistency). Nghĩa là:",
     "Mọi nút bấm phải có màu đỏ.",
     "Sử dụng chung một quy ước về màu sắc, font chữ, vị trí nút bấm, từ vựng trên TẤT CẢ các màn hình của phần mềm.",
     "Giao diện thay đổi ngẫu nhiên.",
     "Mỗi màn hình do 1 người thiết kế tự do.",
     "B"),
    ("Trong thiết kế giao diện, khái niệm 'Feedback' (Phản hồi) mang ý nghĩa gì?",
     "Khách hàng gửi email phàn nàn.",
     "Hệ thống phải luôn thông báo cho người dùng biết chuyện gì đang xảy ra (VD: Hiện thanh loading, thông báo 'Lưu thành công').",
     "Lỗi màn hình xanh.",
     "Tắt tiếng loa máy tính.",
     "B"),
    ("Nguyên lý Liskov Substitution (LSP) trong SOLID nói rằng:",
     "Không được kế thừa.",
     "Lớp con (Subclass) phải có thể thay thế được cho Lớp cha (Superclass) mà không làm hỏng tính đúng đắn của chương trình.",
     "Lớp cha phải xóa lớp con.",
     "Mọi lớp đều phải có chung tên.",
     "B"),
    ("Việc thiết kế 'Kiến trúc Microservices' (Vi dịch vụ) phù hợp cho bài toán nào?",
     "Phần mềm nhúng máy giặt.",
     "Các hệ thống Cloud khổng lồ (như Netflix, Amazon), cần scale độc lập, sử dụng đa ngôn ngữ và có đội ngũ lớn phân tán.",
     "Trang web blog cá nhân.",
     "Phần mềm dùng 1 lần.",
     "B"),
    ("Trong thiết kế kiến trúc phần mềm, 'Trade-off' (Sự đánh đổi) là không thể tránh khỏi. Ví dụ phổ biến là:",
     "Đánh đổi giữa chuột và bàn phím.",
     "Đánh đổi giữa Bảo mật (Security) quá chặt chẽ và Tính dễ dùng (Usability) / Hiệu năng (Performance).",
     "Đánh đổi giữa C++ và HTML.",
     "Đánh đổi giữa Server và Màn hình.",
     "B"),
    ("Kỹ thuật 'Mã giả' (Pseudocode) dùng trong thiết kế thuật toán có đặc điểm gì?",
     "Máy tính có thể chạy trực tiếp.",
     "Kết hợp ngôn ngữ tự nhiên và cấu trúc logic lập trình (if, for, while) giúp diễn đạt giải thuật mà không bị gò bó bởi cú pháp ngôn ngữ cụ thể.",
     "Chỉ được dùng tiếng Anh.",
     "Là mã độc (virus).",
     "B"),
    ("Cấu trúc thiết kế 'God Class' (Lớp chúa trời) là một Anti-pattern (Mẫu thiết kế xấu). Vì sao?",
     "Vì nó không chạy được.",
     "Vì nó là một Class khổng lồ, ôm đồm mọi chức năng của hệ thống, vi phạm Single Responsibility, cực kỳ khó bảo trì.",
     "Vì nó có tên là God.",
     "Vì nó bắt buộc trong MVC.",
     "B"),
    ("Trong quá trình Thiết kế, 'Bảo mật theo thiết kế' (Security by Design) nghĩa là gì?",
     "Giấu tài liệu thiết kế đi.",
     "Các biện pháp bảo mật (phân quyền, mã hóa) phải được kiến trúc và thiết kế ngay từ đầu, chứ không phải là bản vá thêm vào sau khi viết code.",
     "Mua phần mềm diệt virus.",
     "Rút dây mạng khi lập trình.",
     "B"),
    ("Mô hình Kiến trúc Hướng Dịch vụ (SOA - Service Oriented Architecture) tập trung vào điều gì?",
     "Làm dịch vụ bảo hành phần cứng.",
     "Xây dựng hệ thống bằng cách giao tiếp, gọi các Dịch vụ (Services) độc lập qua mạng (thường dùng chuẩn SOAP/REST).",
     "Thiết kế giao diện UI.",
     "Tối ưu hóa RAM.",
     "B"),
    ("Giai đoạn 'Review thiết kế' (Design Review / Walkthrough) nhằm mục đích gì?",
     "Đuổi việc kiến trúc sư.",
     "Tìm kiếm các lỗ hổng kiến trúc, logic sai, hoặc vi phạm yêu cầu trước khi đội code bắt tay vào làm, giúp tiết kiệm chi phí.",
     "Làm tăng độ dày của tài liệu.",
     "Tăng lương cho lập trình viên.",
     "B"),
    ("Trong biểu đồ Lớp (UML), Design Pattern 'Singleton' đảm bảo điều gì?",
     "Mỗi lớp có hàng ngàn đối tượng.",
     "Đảm bảo một Lớp (Class) CHỈ CÓ DUY NHẤT một thể hiện (Instance) tồn tại trong toàn bộ hệ thống và cung cấp 1 điểm truy cập toàn cục.",
     "Xóa mọi đối tượng.",
     "Tạo ra giao diện một cột.",
     "B"),
    ("Mẫu thiết kế 'Observer' (Quan sát viên) thường được dùng trong trường hợp nào?",
     "Để kết nối CSDL.",
     "Xây dựng cơ chế Publish-Subscribe, khi một đối tượng (Subject) thay đổi trạng thái, tất cả các đối tượng theo dõi nó (Observers) sẽ tự động được thông báo (VD: Cập nhật giao diện khi dữ liệu đổi).",
     "Để tính toán cộng trừ.",
     "Để bảo mật mật khẩu.",
     "B"),
    ("Trong nguyên lý SOLID, chữ D (Dependency Inversion Principle) khuyên chúng ta:",
     "Các module cấp cao nên phụ thuộc chặt chẽ vào module cấp thấp.",
     "Các module cấp cao KHÔNG nên phụ thuộc vào module cấp thấp. Cả hai nên phụ thuộc vào Abstraction (Interface). Chi tiết phải phụ thuộc vào trừu tượng.",
     "Không được dùng Interface.",
     "Xóa mọi liên kết phụ thuộc.",
     "B"),
    ("Thiết kế Giao diện (UI) 'Responsive' (Tương thích/Đáp ứng) giải quyết vấn đề gì?",
     "Chống hack giao diện.",
     "Giúp giao diện tự động điều chỉnh bố cục (layout) và kích thước để hiển thị đẹp mắt trên nhiều loại thiết bị (PC, Tablet, Mobile).",
     "Làm web đổi màu theo giờ.",
     "Giảm dung lượng ổ cứng.",
     "B"),
    ("Khi thiết kế CSDL Vật lý, việc tạo 'Index' (Chỉ mục) mang lại lợi ích gì?",
     "Làm CSDL nhỏ lại.",
     "Tăng tốc độ truy vấn (Tìm kiếm/Read) dữ liệu lên rất nhiều lần, nhưng phải đánh đổi bằng tốc độ Ghi/Sửa/Xóa chậm hơn một chút.",
     "Đổi tên cột dữ liệu.",
     "Mã hóa CSDL.",
     "B"),
    ("Một 'Kiến trúc sư phần mềm' (Software Architect) khác biệt lập trình viên (Developer) ở điểm nào?",
     "Viết code nhanh hơn.",
     "Chịu trách nhiệm thiết kế bộ xương tổng thể, lựa chọn công nghệ, đảm bảo các yêu cầu phi chức năng (Performance, Security) thay vì đi sâu viết hàm chi tiết.",
     "Không bao giờ biết code.",
     "Chỉ lo đi họp với khách.",
     "B"),
    ("Nếu Thiết kế Kiến trúc quá tồi, hiện tượng 'Nợ kỹ thuật' (Technical Debt) sẽ:",
     "Giảm dần theo thời gian.",
     "Tích lũy theo cấp số nhân, khiến việc thêm tính năng mới trong tương lai trở nên cực kỳ khó khăn, chậm chạp và dễ sinh bug.",
     "Được ngân hàng trả thay.",
     "Không ảnh hưởng gì.",
     "B"),
    ("Khái niệm 'Refactoring' (Tái cấu trúc) mã nguồn và thiết kế nhằm mục đích gì?",
     "Thay đổi chức năng hệ thống.",
     "Cải thiện chất lượng mã nguồn bên trong (làm sạch code, áp dụng pattern) để dễ bảo trì, nhưng KHÔNG làm thay đổi chức năng bên ngoài của hệ thống.",
     "Chuyển sang ngôn ngữ lập trình mới.",
     "Làm phần mềm chạy chậm đi.",
     "B"),
    ("Tại sao thiết kế phần mềm lại mang tính 'Lặp' (Iterative)?",
     "Vì người vẽ rảnh rỗi.",
     "Vì bản thiết kế hiếm khi hoàn hảo ngay lần đầu. Người ta thường phác thảo, đánh giá, chi tiết hóa rồi lại tinh chỉnh (refine) qua nhiều vòng lặp để đạt tối ưu.",
     "Vì vẽ sai màu.",
     "Vì không có tài liệu.",
     "B"),
    ("Trong thiết kế API (Application Programming Interface), chuẩn RESTful sử dụng cái gì để định danh tài nguyên?",
     "Mã hóa MD5.",
     "Sử dụng các URL (URI) và các phương thức HTTP (GET, POST, PUT, DELETE).",
     "Dùng địa chỉ MAC.",
     "Dùng ổ đĩa C.",
     "B"),
    ("Sự kết dính ngẫu nhiên (Coincidental Cohesion) là dạng kết dính TỒI NHẤT trong thiết kế module. Nó có nghĩa là gì?",
     "Module làm 1 việc duy nhất.",
     "Các hàm bị ném chung vào một module một cách tình cờ, vô nghĩa, không hề có logic liên quan gì với nhau (như file Utils.cs chứa đủ loại hàm).",
     "Module chạy nhanh nhất.",
     "Mọi biến đều liên kết với nhau.",
     "B"),
    ("Mô hình kiến trúc 'Peer-to-Peer' (P2P - Mạng ngang hàng) khác Client-Server ở chỗ nào?",
     "Không dùng mạng Internet.",
     "Không có Server trung tâm. Mỗi nút (Node) trong mạng P2P vừa đóng vai trò là Client yêu cầu dịch vụ, vừa là Server cung cấp dịch vụ cho nút khác (vd: BitTorrent).",
     "Có Server khổng lồ.",
     "Chỉ chạy trên điện thoại.",
     "B"),
    ("Sản phẩm cuối cùng của pha Thiết kế phần mềm (Design Phase) thường là:",
     "Mã nguồn hoàn chỉnh 100%.",
     "Tài liệu Thiết kế Hệ thống (SDD - System Design Document) bao gồm Kiến trúc, CSDL, Giao diện và thuật toán chi tiết.",
     "Hợp đồng kinh tế.",
     "Một đĩa CD rỗng.",
     "B"),
    ("Khi thiết kế cấu trúc dữ liệu, việc lựa chọn List (Mảng) hay Dictionary (Bảng băm) phụ thuộc chủ yếu vào yếu tố nào?",
     "Màu sắc của IDE.",
     "Yêu cầu về hiệu năng thao tác: Cần duyệt tuần tự (dùng List) hay cần tìm kiếm/truy xuất ngẫu nhiên cực nhanh bằng Khóa (dùng Dictionary/Hash map).",
     "Sở thích của quản lý.",
     "Kích thước màn hình.",
     "B"),
    ("Mục tiêu của 'Thiết kế an toàn' (Fail-safe design) là gì?",
     "Tắt nguồn máy tính.",
     "Khi hệ thống gặp lỗi nghiêm trọng (phần cứng/mạng), nó phải kết thúc hoặc chuyển sang trạng thái dự phòng một cách an toàn, không làm hỏng hoặc mất dữ liệu.",
     "Che giấu lỗi với người dùng.",
     "Xóa mọi file log.",
     "B"),
    ("Một 'Giao diện lập trình ứng dụng' (API) được thiết kế tốt sẽ:",
     "Có hàng ngàn tham số phức tạp.",
     "Cung cấp các hàm rõ ràng, dễ hiểu, tài liệu đầy đủ và ẩn đi các chi tiết cài đặt phức tạp bên dưới.",
     "Thay đổi cấu trúc mỗi ngày.",
     "Yêu cầu trả tiền để xem code.",
     "B"),
    ("Trong kiến trúc MVC, nếu View trực tiếp truy vấn CSDL để lấy dữ liệu, thì hệ thống đó:",
     "Hoạt động rất chuẩn mực.",
     "Vi phạm nguyên tắc của MVC, vì View chỉ nên nhận dữ liệu đã xử lý từ Controller/Model, việc truy vấn CSDL là nhiệm vụ của Model.",
     "Chạy nhanh hơn gấp 10 lần.",
     "Là mô hình 4-Tier.",
     "B"),
    ("Một Thiết kế phần mềm được coi là 'Khả chuyển' (Portable) nếu:",
     "Nó có dung lượng nhỏ.",
     "Có thể chuyển hệ thống từ hệ điều hành hoặc phần cứng này sang hệ điều hành/phần cứng khác mà chỉ cần sửa đổi rất ít mã nguồn (hoặc không cần sửa).",
     "Lập trình bằng Assembly.",
     "Nó chỉ chạy trên Windows.",
     "B"),
    ("Tại sao nên ưu tiên 'Composition' (Cấu thành) hơn 'Inheritance' (Kế thừa) trong nhiều trường hợp thiết kế OOP?",
     "Vì kế thừa bị cấm.",
     "Kế thừa tạo ra sự phụ thuộc chặt chẽ ở biên dịch (Tightly coupled), trong khi Composition cho phép lắp ghép và thay đổi hành vi linh hoạt hơn ở thời gian chạy (Runtime).",
     "Vì Composition viết ít code hơn.",
     "Vì CSDL không hiểu kế thừa.",
     "B"),
    ("Khái niệm 'Thừa kế đa hình' (Multiple Inheritance) trong thiết kế lớp là:",
     "Một lớp có nhiều hàm.",
     "Một lớp con có thể kế thừa trực tiếp từ nhiều lớp cha khác nhau (hỗ trợ trong C++ nhưng bị cấm trong Java/C# để tránh xung đột cấu trúc kim cương).",
     "Một người dùng nhiều máy tính.",
     "Không tồn tại.",
     "B"),
    ("Kiến trúc 'Hướng sự kiện' (Event-driven Architecture) hoạt động dựa trên nguyên lý nào?",
     "Gửi email cho khách hàng.",
     "Hệ thống phản ứng với các sự kiện (Events) được sinh ra. Các module không gọi trực tiếp nhau mà lắng nghe (Subscribe) và xử lý sự kiện qua một Event Bus/Broker trung tâm.",
     "Chờ người dùng gõ phím.",
     "Vòng lặp vô hạn.",
     "B"),
    ("Lợi ích của việc sử dụng 'Mẫu thiết kế' (Design Patterns) cho người mới bắt đầu (Juniors) là gì?",
     "Làm họ bối rối và bỏ nghề.",
     "Học hỏi được các 'best practices' đúc kết từ kinh nghiệm của các kỹ sư giỏi, giúp họ giải quyết vấn đề thiết kế chuẩn mực và tránh 'phát minh lại cái bánh xe'.",
     "Làm cho code chạy chậm lại.",
     "Chỉ để đi thi trắc nghiệm.",
     "B"),
    ("Trong Thiết kế Giao diện (UI Design), nguyên tắc 'Cung cấp đường lui' (Forgiveness/Undo) có nghĩa là gì?",
     "Lập trình viên được phép làm sai.",
     "Người dùng rất dễ thao tác nhầm, hệ thống nên có tính năng hoàn tác (Undo) hoặc hộp thoại xác nhận trước khi thực hiện hành động phá hủy dữ liệu (VD: Xóa).",
     "Chửi mắng người dùng.",
     "Xóa ngay lập tức.",
     "B"),
    ("Mẫu thiết kế 'Factory Method' thuộc nhóm Khởi tạo (Creational) giải quyết vấn đề gì?",
     "Xây dựng nhà máy.",
     "Cung cấp một giao diện (Interface) để tạo đối tượng, nhưng để các lớp con quyết định xem lớp nào sẽ được khởi tạo, giúp mã nguồn linh hoạt và không bị 'hard-code' lớp cụ thể.",
     "Kết nối CSDL.",
     "Sắp xếp mảng.",
     "B"),
    ("Việc phân rã hệ thống (Decomposition) quá mức sẽ dẫn đến hệ quả gì?",
     "Hệ thống hoàn hảo.",
     "Mặc dù module nhỏ dễ hiểu, nhưng sự lắp ghép (Coupling/Integration) và số lượng giao tiếp giữa hàng ngàn module quá nhiều sẽ làm tăng độ phức tạp tổng thể.",
     "Dung lượng ổ đĩa giảm.",
     "Tăng kích thước RAM.",
     "B"),
    ("Khi thiết kế CSDL, 'Khóa ngoại' (Foreign Key) phải thỏa mãn ràng buộc toàn vẹn nào?",
     "Tính toàn vẹn tên gọi.",
     "Tính toàn vẹn tham chiếu (Referential Integrity): Giá trị của Khóa ngoại phải tồn tại trong cột Khóa chính của bảng mà nó tham chiếu tới, hoặc phải là NULL.",
     "Tính bảo mật.",
     "Tính đa hình.",
     "B"),
    ("Khái niệm 'Dạng chuẩn 3' (3NF) trong chuẩn hóa cơ sở dữ liệu cấm điều gì?",
     "Cấm dùng kiểu số nguyên.",
     "Cấm sự phụ thuộc bắc cầu (Transitive dependency): Thuộc tính không khóa không được phép phụ thuộc vào một thuộc tính không khóa khác.",
     "Cấm có khóa chính.",
     "Cấm dùng trên web.",
     "B"),
    ("Lớp 'Thực thể' (Entity Class) trong thiết kế hướng đối tượng có nhiệm vụ:",
     "Vẽ giao diện lên màn hình.",
     "Lưu trữ dữ liệu và trạng thái của các thực thể nghiệp vụ (VD: SinhVien, HoaDon), thường được ánh xạ (map) trực tiếp xuống các bảng trong CSDL.",
     "Xử lý bắt lỗi mạng.",
     "Điều khiển chuột.",
     "B"),
    ("Lớp 'Điều khiển' (Control Class / Controller) xử lý vấn đề gì?",
     "Lưu trữ dữ liệu.",
     "Điều phối luồng công việc (Workflow), tính toán logic nghiệp vụ phức tạp, nhận Input từ Boundary và cập nhật vào Entity.",
     "Chỉ hiển thị màu sắc.",
     "Làm tăng RAM.",
     "B"),
    ("Sự kết dính Chức năng (Functional Cohesion) là dạng kết dính TỐT NHẤT. Nó có nghĩa là gì?",
     "Mọi thứ dồn vào 1 hàm.",
     "Mọi thành phần bên trong module đều đóng góp vào việc thực hiện MỘT VÀ CHỈ MỘT chức năng / nhiệm vụ duy nhất (Ví dụ: Module Tính căn bậc 2).",
     "Module gọi tất cả các module khác.",
     "Không có liên kết nào.",
     "B"),
    ("Sự kết dính Logic (Logical Cohesion) là gì?",
     "Là sự kết dính hoàn hảo.",
     "Các thành phần được gom vào 1 module chỉ vì chúng có chung bản chất logic (VD: Hàm 'In', tham số truyền vào là in ra Màn hình hay in ra Giấy thì rẽ nhánh If/Else).",
     "Chạy bằng toán học.",
     "Màu sắc giống nhau.",
     "B"),
    ("Khái niệm 'Ghép nối dữ liệu' (Data Coupling) là mức độ ghép nối TỐT NHẤT (lỏng lẻo nhất). Đặc điểm của nó là:",
     "Dùng chung một biến toàn cục khổng lồ.",
     "Hai module giao tiếp với nhau bằng cách TRUYỀN THAM SỐ (Parameters) là các dữ liệu đơn giản, không truyền cấu trúc phức tạp hay luồng điều khiển.",
     "Truyền lệnh if-else cho nhau.",
     "Không truyền gì cả.",
     "B"),
    ("Ghép nối Nội dung (Content Coupling) là mức độ TỒI NHẤT. Khi nào nó xảy ra?",
     "Khi gửi email.",
     "Khi Module A truy cập, sử dụng hoặc sửa đổi trực tiếp dữ liệu/mã nguồn bên trong của Module B (Bỏ qua hoàn toàn sự đóng gói/Encapsulation).",
     "Khi truyền 1 biến int.",
     "Khi 2 module ở 2 máy tính khác nhau.",
     "B"),
    ("Ghép nối Môi trường chung (Common / Global Coupling) có đặc điểm gì?",
     "Các module chạy chung 1 hệ điều hành.",
     "Nhiều module cùng truy cập và chia sẻ chung một vùng dữ liệu toàn cục (Global Variables), khiến việc theo dõi module nào đã sửa dữ liệu rất khó khăn.",
     "Chung mạng LAN.",
     "Chung ngôn ngữ lập trình.",
     "B"),
    ("Trong Thiết kế Giao diện (UI), nguyên tắc 'Giảm tải nhận thức' (Reduce Cognitive Load) có nghĩa là:",
     "Bắt người dùng học thuộc 100 phím tắt.",
     "Giao diện phải trực quan, dễ nhớ, không bắt người dùng phải ghi nhớ quá nhiều thông tin từ màn hình này sang màn hình khác.",
     "Làm giao diện thật nhiều chữ.",
     "Giảm độ sáng màn hình.",
     "B"),
    ("Nếu một ứng dụng có giao diện quá chậm (lag) do phải xử lý tính toán lớn, Kiến trúc sư nên thiết kế thế nào?",
     "Bảo khách hàng đổi máy tính.",
     "Thiết kế xử lý tính toán ở chế độ chạy nền (Background thread/Asynchronous) và trả lại quyền điều khiển giao diện (UI thread) ngay lập tức để ứng dụng không bị 'đơ'.",
     "Xóa bớt tính năng.",
     "Giảm màu sắc xuống trắng đen.",
     "B"),
    ("Việc xây dựng một 'Từ điển Dữ liệu' (Data Dictionary) trong Thiết kế CSDL dùng để làm gì?",
     "Dịch văn bản.",
     "Định nghĩa tập trung và thống nhất mọi thuật ngữ, kiểu dữ liệu, kích thước, ràng buộc của tất cả các phần tử dữ liệu trong hệ thống, tránh xung đột.",
     "Mã hóa CSDL.",
     "Tính toán dung lượng ổ cứng.",
     "B"),
    ("Khái niệm 'Thin Client' (Khách hàng mỏng) trong kiến trúc Client-Server nghĩa là:",
     "Màn hình máy tính rất mỏng.",
     "Phần mềm Client chỉ đảm nhận việc hiển thị giao diện (VD: Trình duyệt web), toàn bộ tính toán logic và dữ liệu đều do Server xử lý.",
     "Khách hàng ít tiền.",
     "Server rất nhỏ.",
     "B"),
    ("Ngược lại, 'Fat Client' (Khách hàng béo/dày) nghĩa là gì?",
     "Máy tính to và nặng.",
     "Client chứa cả giao diện và phần lớn logic xử lý nghiệp vụ, Server chủ yếu chỉ đóng vai trò lưu trữ CSDL (VD: Các phần mềm Desktop truyền thống cài trên Windows).",
     "Khách hàng có nhiều tiền.",
     "Máy chủ rất lớn.",
     "B"),
    ("Để đáp ứng yêu cầu 'Tính Khả dụng cao' (High Availability) cho hệ thống, kiến trúc sư nên thiết kế:",
     "Mua máy tính thật đắt.",
     "Sử dụng cơ chế Cụm máy chủ (Clustering), Cân bằng tải (Load Balancing) và Dữ liệu dự phòng (Redundancy) để nếu 1 Server chết, Server khác sẽ thay thế ngay.",
     "Thiết kế giao diện đẹp.",
     "Viết code ngắn lại.",
     "B"),
    ("Nguyên lý 'Interface Segregation' (ISP - Phân tách Giao diện) trong SOLID khuyên gì?",
     "Xóa mọi giao diện.",
     "Không nên ép một lớp phải cài đặt (implement) các giao diện (hàm) mà nó không sử dụng. Hãy tách các Giao diện lớn thành các Giao diện nhỏ, chuyên biệt hơn.",
     "Dùng chung 1 giao diện cho mọi lớp.",
     "Làm giao diện web.",
     "B"),
    ("Thiết kế 'Asynchronous' (Bất đồng bộ) xử lý công việc bằng cách nào?",
     "Dừng máy tính chờ xong việc.",
     "Chuyển công việc nặng sang chạy nền, trả ngay phản hồi cho luồng chính (Main/UI Thread) để hệ thống không bị 'đóng băng' (blocking).",
     "Từ chối công việc nặng.",
     "Chia công việc cho người dùng làm.",
     "B"),
    ("Thiết kế 'Lấy dữ liệu làm trung tâm' (Data-Centric Design) có nhược điểm gì nếu lạm dụng?",
     "Mất nhiều điện năng.",
     "Dễ biến hệ thống phần mềm thành một 'Cái vỏ' chỉ để CRUD CSDL (Anemic Domain Model), bỏ qua việc đóng gói các luồng nghiệp vụ phức tạp vào Đối tượng.",
     "Chạy quá nhanh.",
     "Dung lượng đĩa không đủ.",
     "B"),
    ("Khi nói về bảo mật (Security), nguyên tắc 'Least Privilege' (Quyền hạn tối thiểu) khuyên nhà thiết kế:",
     "Cho mọi người quyền Admin.",
     "Mỗi module, user, hoặc đoạn code chỉ nên được cấp ĐÚNG quyền hạn tối thiểu cần thiết để thực thi nhiệm vụ của nó, không hơn.",
     "Cấm tất cả mọi người dùng phần mềm.",
     "Không cấp quyền cho ai.",
     "B"),
    ("Mô hình 'Nhà xuất bản - Người đăng ký' (Publish-Subscribe) thường dùng để xử lý cái gì?",
     "In báo giấy.",
     "Hệ thống truyền tải tin nhắn/sự kiện phân tán. Publisher bắn sự kiện, Subscriber nhận sự kiện, chúng không cần biết trực tiếp về nhau (Decoupling).",
     "Gửi email thủ công.",
     "Bảo mật CSDL.",
     "B"),
    ("Thiết kế Giao diện (UI) thường xuyên áp dụng 'Nguyên tắc Gestalt' trong tâm lý học để làm gì?",
     "Điều trị bệnh tâm lý.",
     "Thiết kế bố cục (Layout): Các nút bấm hoặc thông tin có liên quan logic sẽ được nhóm gần nhau (Proximity) hoặc giống nhau (Similarity) để não bộ tự động hiểu chúng là một nhóm.",
     "Lập trình thuật toán AI.",
     "Tăng tốc độ CPU.",
     "B"),
    ("Việc thiết kế một 'Tầng Truy xuất Dữ liệu' (Data Access Layer - DAL) trong mô hình 3-Tier nhằm:",
     "Vẽ giao diện hiển thị.",
     "Gom toàn bộ logic kết nối DB, câu lệnh SQL vào một chỗ. Tầng Business ở trên không cần biết DB dùng MySQL hay Oracle, chỉ cần gọi hàm của DAL.",
     "Lưu trữ ảnh.",
     "Bảo mật mật khẩu UI.",
     "B"),
    ("Mẫu thiết kế 'Adapter' (Bộ chuyển đổi) có công dụng gì?",
     "Sạc pin cho laptop.",
     "Làm trung gian chuyển đổi Interface của một lớp có sẵn thành một Interface khác mà hệ thống hiện tại mong muốn (giống phích cắm điện chuyển đổi).",
     "Bắt wifi cho máy chủ.",
     "Diệt virus.",
     "B"),
    ("Nguyên tắc 'Keep It Simple, Stupid' (KISS) có nghĩa là:",
     "Chỉ thuê lập trình viên ngốc.",
     "Sự đơn giản luôn luôn chiến thắng. Một thiết kế phức tạp không cần thiết là một thiết kế tồi, vì nó mang lại rủi ro lỗi và chi phí bảo trì khổng lồ.",
     "Lập trình rất khó.",
     "Không làm gì cả.",
     "B"),
    ("Kiến trúc 'Hexagonal Architecture' (Kiến trúc lục giác / Ports and Adapters) bảo vệ cái gì làm trung tâm?",
     "Cơ sở dữ liệu.",
     "Logic Nghiệp vụ Cốt lõi (Core Domain Logic) nằm ở giữa, độc lập hoàn toàn với Giao diện (Web/Mobile) và CSDL/Hệ thống ngoài, giao tiếp qua Port và Adapter.",
     "Giao diện người dùng.",
     "Máy chủ vật lý.",
     "B"),
    ("Một hàm trong Lớp tính toán (Control Class) vừa tính toán lãi suất, vừa in dòng chữ ra màn hình, vừa lưu vào CSDL. Hàm này vi phạm mạnh nguyên lý gì?",
     "DRY.",
     "Nguyên lý Đơn trách nhiệm (Single Responsibility Principle - SRP) và có mức độ kết dính rất kém.",
     "LSP.",
     "OCP.",
     "B"),
    ("Kiến trúc 'Stateless' (Không trạng thái) trong API / Web Server mang lại lợi ích gì?",
     "Tắt Server đi ngay sau khi phản hồi.",
     "Server không lưu trạng thái (session) của Client giữa các lần request. Nhờ vậy, ta có thể dễ dàng scale (thêm hàng loạt server) mà không lo lỗi đồng bộ session.",
     "Tốn nhiều RAM hơn.",
     "Phải khởi động lại liên tục.",
     "B"),
    ("Mục đích của việc Thiết kế Thuật toán (Algorithm Design) trước khi code là:",
     "Làm tăng số lượng dòng code.",
     "Đảm bảo thuật toán là tối ưu về mặt Thời gian (Time Complexity - Big O) và Bộ nhớ (Space) trước khi cắm đầu vào gõ lệnh cụ thể.",
     "Biến thuật toán thành phần cứng.",
     "Làm màu sắc giao diện đẹp hơn.",
     "B"),
    ("Sự kết dính Thông tin (Informational Cohesion) là dạng kết dính tốt, đặc điểm của nó là:",
     "Cùng đọc chung một quyển báo.",
     "Các thao tác bên trong module thực thi các chức năng khác nhau nhưng trên CÙNG MỘT cấu trúc dữ liệu / thông tin dùng chung (Đây chính là đặc tính của Class trong OOP).",
     "Không có dữ liệu.",
     "Truyền tin qua mạng internet.",
     "B"),
    ("Khi hai module giao tiếp với nhau bằng cách truyền CẤU TRÚC DỮ LIỆU phức tạp (vd: cả một Object bự) dù chỉ cần 1 trường nhỏ, đó gọi là:",
     "Ghép nối Nội dung.",
     "Ghép nối Dấu (Stamp Coupling) / Ghép nối Cấu trúc - Làm tăng sự phụ thuộc không cần thiết vào toàn bộ cấu trúc.",
     "Ghép nối Dữ liệu (Tốt).",
     "Ghép nối Môi trường.",
     "B"),
    ("Trong Thiết kế CSDL vật lý, kỹ thuật 'Sharding' (Phân mảnh) dùng để:",
     "Xóa CSDL nhanh.",
     "Chia nhỏ một CSDL khổng lồ (hàng tỷ bản ghi) ra thành nhiều phần (Shards) lưu trên các máy chủ vật lý khác nhau để tăng tốc độ truy xuất và giảm tải.",
     "Tạo bảng mới.",
     "Gộp 10 bảng thành 1.",
     "B"),
    ("Đâu là một ví dụ về 'Anti-Pattern' (Thiết kế lỗi) mang tên 'Spaghetti Code'?",
     "Code có màu giống mì Ý.",
     "Mã nguồn có sự kiểm soát luồng điều khiển (if, goto, call) đan chéo chằng chịt, không có cấu trúc phân tầng hay module rõ ràng, hoàn toàn không thể hiểu và bảo trì.",
     "Chỉ có 1 dòng code.",
     "Code chạy quá nhanh.",
     "B"),
    ("Thiết kế CSDL logic (Logical Database Design) có đặc điểm gì?",
     "Nó yêu cầu biết số vòng quay ổ cứng.",
     "Nó chuyển đổi mô hình thực thể ERD thành dạng bảng (Relation) nhưng vẫn độc lập với Hệ quản trị CSDL cụ thể (SQL Server, MySQL...).",
     "Chỉ vẽ bằng tay.",
     "Không liên quan đến phần mềm.",
     "B"),
    ("Khái niệm 'Đảo ngược luồng điều khiển' (Inversion of Control - IoC) trong Framework mang ý nghĩa gì?",
     "Làm chuột máy tính chạy ngược.",
     "Bạn không phải gọi mã của Framework (như Library); Framework sẽ quyết định khi nào và gọi lại (callback) đoạn mã do bạn viết theo một luồng định sẵn.",
     "Xóa bỏ hàm chính.",
     "Tạo lỗi mạng.",
     "B"),
    ("Thiết kế 'Giao tiếp bằng thông điệp' (Message-Oriented Middleware - MOM) giải quyết khó khăn gì trong Hệ thống phân tán?",
     "Khó khăn về tốc độ gõ phím.",
     "Giúp các ứng dụng không cần biết địa chỉ IP của nhau. Chúng gửi thông điệp vào Hàng đợi (Message Queue) như RabbitMQ/Kafka, đảm bảo hệ thống không bị treo nếu bên nhận sập tạm thời.",
     "Mất nhiều điện.",
     "Màn hình bị đen.",
     "B"),
    ("Mô hình kiến trúc 'Repository' (Kho dữ liệu trung tâm) thường gặp trong lĩnh vực nào?",
     "Làm game.",
     "Các hệ thống quản lý tri thức, IDE (Môi trường phát triển), nơi rất nhiều công cụ (Trình biên dịch, Trình phân tích cú pháp) cùng thao tác trên 1 kho cây cú pháp (AST) chung.",
     "Viết thư điện tử.",
     "Phát nhạc.",
     "B"),
    ("Kiến trúc 'Model-View-Controller' (MVC) trên web thường sử dụng công nghệ gì cho thành phần View?",
     "SQL Server.",
     "HTML, CSS, JavaScript (Render trên trình duyệt) hoặc các Template Engine (JSP, Razor) render trên Server.",
     "Ngôn ngữ Assembly.",
     "Card màn hình rời.",
     "B"),
    ("Trong thiết kế hướng cấu trúc (Structural Design), sơ đồ nào mô tả cây cấu trúc gọi hàm (Calling hierarchy)?",
     "Sơ đồ ERD.",
     "Sơ đồ cấu trúc (Structure Chart) - mô tả module cha gọi các module con nào.",
     "Biểu đồ Use-case.",
     "Sơ đồ mạng.",
     "B"),
    ("Một module có 'Độ kết dính thời gian' (Temporal Cohesion) khi nào?",
     "Nó theo dõi giờ thế giới.",
     "Các lệnh trong module không liên quan nhau về logic, chỉ bị gộp chung vào 1 hàm vì chúng cần phải thực thi CÙNG MỘT LÚC (ví dụ: Hàm Initialize() khởi tạo mạng, biến, csdl).",
     "Chạy bằng đồng hồ.",
     "Kiểm tra ngày nghỉ lễ.",
     "B"),
    ("Việc phân rã 'Decomposition' theo phương pháp Hướng đối tượng dựa trên:",
     "Theo từng hàm toán học.",
     "Dựa trên cấu trúc sự vật, danh từ trong thế giới thực (Classes/Objects), đóng gói cả dữ liệu và hành vi thay vì chỉ chia nhỏ hàm xử lý.",
     "Chia nhỏ phần cứng máy chủ.",
     "Chia theo màu sắc giao diện.",
     "B"),
    ("Mẫu thiết kế 'Abstract Factory' (Nhà máy trừu tượng) được sử dụng để:",
     "In file giấy.",
     "Cung cấp một Giao diện để tạo ra MỘT HỌ (Family) các đối tượng có liên quan hoặc phụ thuộc nhau mà không cần chỉ định các lớp cụ thể của chúng.",
     "Sửa lỗi kết nối mạng.",
     "Xóa CSDL.",
     "B"),
    ("Mô hình kiến trúc 'Lục giác' (Ports and Adapters) hướng tới mục tiêu chính là gì?",
     "Hình dạng lục giác đẹp hơn hình tròn.",
     "Tách rời (Decouple) hoàn toàn Core Logic nghiệp vụ khỏi các yếu tố thay đổi như Giao diện người dùng (Web/Mobile) và Cơ sở dữ liệu (SQL/NoSQL).",
     "Làm tăng thời gian tải trang.",
     "Mã hóa màn hình.",
     "B"),
    ("Mẫu thiết kế 'Builder' (Người xây dựng) có nhiệm vụ:",
     "Gõ mã nguồn.",
     "Tách biệt quá trình xây dựng/khởi tạo một đối tượng PHỨC TẠP ra khỏi cấu trúc của nó, cho phép cùng một quá trình có thể tạo ra các thể hiện khác nhau.",
     "Vẽ giao diện HTML.",
     "Dịch chương trình sang Assembly.",
     "B"),
    ("Mẫu thiết kế 'Iterator' (Biến duyệt) thuộc nhóm Hành vi có tác dụng:",
     "Ngăn chặn vòng lặp.",
     "Cung cấp cách thức truy xuất tuần tự các phần tử của một tập hợp (như List, Tree) mà không để lộ cấu trúc bên trong (danh sách hay mảng) của tập hợp đó.",
     "Tính toán công thức toán.",
     "Hiển thị bảng giá.",
     "B"),
    ("Để hệ thống dễ 'Bảo trì', khi thiết kế mã nguồn, người ta thường cố gắng tránh:",
     "Sự ngăn nắp (Clean code).",
     "Sự 'Mã hóa cứng' (Hard-coding). Ví dụ: Nhúng trực tiếp đường dẫn CSDL hoặc tham số IP thẳng vào trong mã nguồn thay vì để vào file cấu hình (Config).",
     "Thiết kế Interface.",
     "Áp dụng nguyên lý SOLID.",
     "B"),
    ("Thiết kế 'Concurrency' (Đồng thời) đòi hỏi kỹ sư phải đối mặt với khó khăn cốt lõi nào?",
     "Lỗi giao diện xấu.",
     "Các vấn đề về Đua tranh dữ liệu (Race conditions), Bế tắc (Deadlocks) khi nhiều luồng/tiến trình cùng đọc và ghi vào một biến/dữ liệu cùng lúc.",
     "Tốn dung lượng đĩa.",
     "Máy tính chạy quá nhanh.",
     "B"),
    ("Khi hai module A và B giao tiếp bằng cách truyền một biến cờ (Flag) như: 'isError', 'type=1'. Lúc này B phải rẽ nhánh if/else theo biến cờ. Đó là dạng ghép nối gì?",
     "Data Coupling.",
     "Control Coupling (Ghép nối điều khiển). Module A kiểm soát một phần logic xử lý bên trong của Module B.",
     "Stamp Coupling.",
     "Common Coupling.",
     "B"),
    ("Kiến trúc 'Pipes and Filters' mang lại lợi ích gì?",
     "Giao diện người dùng sinh động.",
     "Mỗi Filter cực kỳ độc lập (High Cohesion, Low Coupling), chúng ta có thể dễ dàng cắm rút, đổi thứ tự các Filter hoặc thêm bộ lọc mới mà không ảnh hưởng toàn hệ thống.",
     "Dung lượng phần mềm cực nhẹ.",
     "Chỉ phù hợp với web.",
     "B"),
    ("Sơ đồ Lớp ở giai đoạn Thiết kế (Design Class Diagram) khác ở giai đoạn Phân tích ở điểm nào?",
     "Sơ đồ thiết kế bị xóa sạch thuộc tính.",
     "Sơ đồ thiết kế CỤ THỂ HÓA chi tiết kiểu dữ liệu, mức truy cập (+, -, #), bổ sung các lớp công nghệ (UI, Database, Helper) và áp dụng Design Patterns.",
     "Chỉ vẽ bằng bút đỏ.",
     "Chỉ có 1 lớp.",
     "B"),
    ("Kỹ thuật 'Dependency Injection' (DI) được coi là một cách áp dụng Design Pattern nào?",
     "Singleton Pattern.",
     "Inversion of Control (IoC) - Chuyển giao quyền khởi tạo phụ thuộc.",
     "Factory Method.",
     "Observer.",
     "B"),
    ("Thiết kế Giao diện (UI) theo quy luật 'Fitts's Law' (Định luật Fitts) khuyên gì?",
     "Chỉ dùng màn hình nhỏ.",
     "Các đối tượng người dùng thao tác nhiều (như Nút Mua hàng) nên được làm TO HƠN và đặt GẦN con trỏ chuột/ngón tay nhất có thể để giảm thời gian thao tác.",
     "Giao diện không nên có nút bấm.",
     "Màu nền luôn là đen.",
     "B"),
    ("Mô hình kiến trúc phân tầng cổ điển OSI (Mạng lưới viễn thông) có bao nhiêu tầng (Layers)?",
     "3 tầng.",
     "7 tầng.",
     "5 tầng.",
     "2 tầng.",
     "B"),
    ("Kiến trúc 'Master-Slave' (Chủ - Tớ) thường ứng dụng ở đâu?",
     "Xây dựng Web.",
     "Các hệ thống song song hoặc Hệ thống kiểm soát tính toán khổng lồ. Server Chủ phân chia công việc cho các Server Tớ tính toán rồi gộp kết quả lại (VD: Database replication).",
     "Lập trình Game 2D cá nhân.",
     "Không ứng dụng ở đâu.",
     "B"),
    ("Tại sao Thiết kế Hệ thống lại phải tính đến 'Lỗi của con người' (Human Errors)?",
     "Vì máy tính không bao giờ lỗi.",
     "Vì người dùng luôn có xu hướng nhập sai dữ liệu, click nhầm. Thiết kế tốt (Fail-safe, Validation, Undo) ngăn chặn những sai lầm đó phá hỏng CSDL của hệ thống.",
     "Để trừ lương người dùng.",
     "Để chương trình tự viết lại code.",
     "B"),
    ("Mô hình phát triển 'Agile' nhìn nhận việc 'Thiết kế' như thế nào?",
     "Từ chối hoàn toàn việc thiết kế.",
     "Thiết kế diễn ra liên tục (Continuous Design) và linh hoạt (Emergent Architecture) thay vì làm một cục tài liệu thiết kế khổng lồ ở đầu dự án (Big Design Up Front).",
     "Bắt buộc dùng Thác nước.",
     "Thiết kế chỉ dành cho phần cứng.",
     "B"),
    ("Để tăng cường độ 'Bảo mật' (Security) trong thiết kế, người ta KHÔNG nên làm điều gì?",
     "Mã hóa mật khẩu.",
     "Lưu thông tin đăng nhập quan trọng trực tiếp ở Client (Trình duyệt/Mobile) thay vì xử lý trên Server.",
     "Phân quyền người dùng (Authorization).",
     "Xác thực kỹ càng (Authentication).",
     "B"),
    ("Trong Thiết kế CSDL, quá trình 'Mapping' (Ánh xạ) từ Object sang Relation Database gọi là gì?",
     "DFD.",
     "ORM (Object-Relational Mapping). Framework (như Hibernate, Entity Framework) sẽ tự động sinh lệnh SQL chuyển đổi giữa Lớp đối tượng và Bảng CSDL.",
     "XML.",
     "API.",
     "B"),
    ("Lý do quan trọng nhất phải 'Design before Code' (Thiết kế trước khi Code) là:",
     "Để thỏa mãn quy trình công ty.",
     "Giảm thiểu sai sót đắt đỏ, định hình cấu trúc rõ ràng, cho phép phân chia công việc cho nhiều người cùng làm, thay vì code lộn xộn không kiểm soát.",
     "Lập trình viên không biết viết code.",
     "Tăng kích thước dự án.",
     "B"),
    ("Khái niệm 'Mẫu kiến trúc' (Architectural Pattern) khác 'Mẫu thiết kế' (Design Pattern) ở điểm nào?",
     "Không có gì khác biệt.",
     "Mẫu kiến trúc áp dụng cho mức độ vĩ mô, toàn bộ hệ thống (VD: MVC, Microservices). Mẫu thiết kế áp dụng cho mức vi mô, xử lý cục bộ giữa vài Class (VD: Singleton, Observer).",
     "Mẫu kiến trúc dùng cho phần cứng.",
     "Mẫu thiết kế vẽ bằng UML.",
     "B"),
    ("Kỹ thuật 'Sharding' trong thiết kế kiến trúc hệ thống dữ liệu lớn có tác dụng gì?",
     "Xóa dữ liệu cũ.",
     "Chia nhỏ một CSDL khổng lồ ra nhiều mảnh (Shard) và lưu trên nhiều máy chủ vật lý khác nhau để tăng tốc độ phân tán.",
     "Gộp nhiều bảng thành 1.",
     "Thay đổi cấu trúc CSDL.",
     "B"),
    ("Trong thiết kế UI/UX, 'Khoảng trắng' (White space/Negative space) mang lại lợi ích gì?",
     "Làm lãng phí diện tích màn hình.",
     "Giúp mắt người dùng được nghỉ ngơi, tạo sự phân tách rõ ràng giữa các thành phần giao diện, làm giao diện sang trọng và dễ đọc hơn.",
     "Làm tăng tốc độ mạng.",
     "Làm lỗi màn hình LCD.",
     "B"),
    ("Khi thiết kế phần mềm, nguyên tắc 'Fail-fast' (Thất bại sớm) khuyên lập trình viên nên làm gì?",
     "Chạy chậm lại.",
     "Nếu phát hiện điều kiện đầu vào sai hoặc lỗi không thể phục hồi, hãy dừng chương trình và báo lỗi NGAY LẬP TỨC thay vì để dữ liệu rác chạy sâu vào hệ thống.",
     "Lờ đi lỗi đó.",
     "Tắt màn hình.",
     "B"),
    ("Thiết kế 'API' (Giao diện lập trình ứng dụng) phải đảm bảo nguyên tắc 'Backward Compatibility' (Tương thích ngược). Nghĩa là gì?",
     "Code phải chạy lùi.",
     "Khi API nâng cấp phiên bản mới, nó không được làm hỏng các phần mềm Client cũ đang gọi phiên bản API trước đó.",
     "Đổi tên hàm liên tục.",
     "Xóa các tính năng cũ.",
     "B"),
    ("Trong thiết kế hệ thống, 'Single Point of Failure' (Điểm lỗi đơn lẻ - SPOF) là gì?",
     "Là điểm bắt đầu chạy chương trình.",
     "Một thành phần duy nhất trong hệ thống mà nếu nó hỏng, TOÀN BỘ hệ thống sẽ sụp đổ (Ví dụ: Chỉ có 1 máy chủ CSDL duy nhất). Thiết kế tốt phải loại bỏ SPOF.",
     "Là tính năng xóa lỗi.",
     "Là lỗi do lập trình viên.",
     "B"),
    ("Để loại bỏ 'Điểm lỗi đơn lẻ' (SPOF) ở tầng Máy chủ CSDL, người ta thường thiết kế cơ chế gì?",
     "Dùng máy chủ cũ.",
     "Sử dụng kỹ thuật 'Sao lưu đồng bộ' (Replication) hoặc Cụm máy chủ (Database Clustering). Nếu Server chính (Primary) sập, Server phụ (Replica) sẽ tự động lên thay.",
     "Cài thêm RAM.",
     "Giảm dung lượng ổ cứng.",
     "B"),
    ("Thiết kế 'Trạng thái' (Stateful) và 'Không trạng thái' (Stateless) cho Server Web có ảnh hưởng gì lớn nhất?",
     "Ảnh hưởng màu sắc Web.",
     "Server Stateless (như REST) không lưu thông tin Session của Client, do đó có thể dễ dàng thêm hàng trăm Server chạy song song (Horizontal Scaling) mà không sợ lỗi.",
     "Làm giảm tốc độ bàn phím.",
     "Làm tốn điện năng.",
     "B"),
    ("Trong nguyên lý SOLID, nguyên lý 'Liskov Substitution Principle' (LSP) đảm bảo điều gì về mặt Thiết kế Hướng đối tượng?",
     "Cấm dùng Kế thừa.",
     "Đảm bảo việc Kế thừa là đúng đắn: Lớp con phải có thể sử dụng thay thế được cho Lớp cha ở mọi chỗ mà không làm sai lệch tính đúng đắn của chương trình.",
     "Lớp con xóa lớp cha.",
     "Không dùng interface.",
     "B"),
    ("Mô hình kiến trúc 'Monolithic' (Nguyên khối) có một ưu điểm lớn ở GIAI ĐOẠN ĐẦU của dự án là gì?",
     "Tốc độ mạng cực nhanh.",
     "Dễ phát triển, dễ test toàn cục, và dễ triển khai (Deploy) vì tất cả chỉ là 1 khối mã nguồn duy nhất, không phải cấu hình mạng phức tạp như Microservices.",
     "Không bao giờ bị lỗi.",
     "Tự động sinh mã nguồn.",
     "B"),
    ("Tuy nhiên, khi dự án Monolithic (Nguyên khối) phình to sau 5 năm, nó gặp phải 'Ác mộng' lớn nhất là gì?",
     "Chạy tốn nhiều điện.",
     "Thời gian biên dịch quá lâu, một sửa đổi nhỏ có thể làm sụp cả hệ thống, và cực kỳ khó khăn khi chỉ muốn nâng cấp riêng 1 công nghệ (như DB) cho 1 chức năng.",
     "Không tương thích chuột máy tính.",
     "Bị virus tấn công.",
     "B"),
    ("Thiết kế kiến trúc 'Micro-kernel' (Nhân vi mô / Plugin Architecture) được sử dụng nổi tiếng nhất ở đâu?",
     "Trong việc thiết kế CSDL.",
     "Trong các Hệ điều hành (Linux, Windows) hoặc các IDE (Eclipse, VS Code), nơi có một phần Lõi nhỏ gọn ổn định, và mở rộng tính năng qua các Plugins.",
     "Chỉ dùng cho Web.",
     "Trong máy tính bỏ túi.",
     "B"),
    ("Trong Thiết kế CSDL, 'Tính toàn vẹn Dữ liệu' (Data Integrity) đảm bảo điều gì?",
     "Dữ liệu đẹp mắt.",
     "Đảm bảo dữ liệu lưu trong hệ thống luôn luôn chính xác, đồng nhất và tuân thủ các luật nghiệp vụ (VD: Tuổi không được âm, Khóa ngoại không trỏ vào số ảo).",
     "Dữ liệu mã hóa 100%.",
     "Không giới hạn dung lượng.",
     "B"),
    ("Kỹ thuật thiết kế 'Tải trễ' (Lazy Loading) giúp ích gì cho giao diện người dùng?",
     "Làm người dùng đợi lâu hơn.",
     "Giúp ứng dụng khởi động cực nhanh bằng cách chỉ tải cấu trúc cơ bản, các dữ liệu nặng (như hình ảnh phía dưới trang) chỉ được tải khi người dùng cuộn (scroll) tới.",
     "Tự động xóa dữ liệu.",
     "Tắt màn hình.",
     "B")
]

new_part2_content = ""
for i, (q, a, b, c, d, ans) in enumerate(questions, 1):
    new_part2_content += f"**Câu {i}:** {q}\n"
    new_part2_content += f"A. {a}\nB. {b}\nC. {c}\nD. {d}\n*Đáp án: {ans}*\n\n"

# Replace the entire part 2
import re
with open("chương 5.md", "r", encoding="utf-8") as f:
    text = f.read()

parts = text.split("## PHẦN 2: Câu hỏi trắc nghiệm (Multiple Choice)")
part1 = parts[0]

with open("chương 5.md", "w", encoding="utf-8") as f:
    f.write(part1 + "## PHẦN 2: Câu hỏi trắc nghiệm (Multiple Choice)\n\n" + new_part2_content)

